### ISSUE TITLE
Bug: Immortal unnamed Valar/Istari/Nazgul courtiers are back (again!) 

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#430]
Jamie-san hijacking Juke's post to add a checklist on this... 👻

- [x] Fix Radagast's court spawning Istari on game start
- [x] Fix Fallen Istari characters not getting converted on the annual pulse.

Edit: Scroll down for the modern issue, this is an old one i reopened.

Compatch branch. not sure if theres like a way for me to mark this.
Immortal unnamed valar courtiers are back in action baby!.

![image](https://user-images.githubusercontent.com/76008882/173232263-784339f8-401d-4ca4-8b71-5d2677ed993f.png)

Apparently, Grimbeorn and his gang also made it over. Probably just files that were falsely copied over or something

![image](https://user-images.githubusercontent.com/76008882/173232584-240ecfa3-f2e1-4f41-8560-1d2f6167582c.png)

**Comment by Remerod** [comment]
Juke tells me this is fixed

![image](https://user-images.githubusercontent.com/79544635/178312880-fdc05354-99df-4b44-a4c3-6622d995f33f.png)

**Comment by JukeJukestar** [comment]
![Skarmbild_2022-10-19_173314](https://user-images.githubusercontent.com/76008882/196751156-0c3c92b9-6069-45c3-97c1-d1291dfa78d7.png)

the return of the king! This was posted by a user in discord playing as Abrakhan.
Seems likely this is from an event added by friends and foes, one that summons powerful courtiers of a certain skill. (Similar to the knights you get from your marshal for example)

**Comment by jj248** [comment]
On latest build, I'm not seeing any instances of Fallen Maiar, Valar or Ringwraiths appearing:
![image](https://user-images.githubusercontent.com/26043074/220896255-2f7b5a3e-79b0-4145-a77a-998a0dae7903.png)

We do have an issue with Istari, but this is due to being spawned in Radagast's court on game start:
![image](https://user-images.githubusercontent.com/26043074/220896502-c82ce8c3-ba90-48a7-a1b2-d25f3cb12503.png)

We also have an issue with Fallen Istari not being converted:
![image](https://user-images.githubusercontent.com/26043074/220896880-82573f6e-6fba-4c01-9444-4e12b4c7058e.png)

**Comment by jj248** [comment]
Should have fixed these two issues.  Over to testing.

**Comment by Jauffr** [comment]
This issue is still happening 
![Screenshot 2023-02-24 183057](https://user-images.githubusercontent.com/108106660/221332218-feba642f-0846-4b2f-ba4a-b5e68c028af3.png)

**Comment by jj248** [comment]
Feck.  Just in good Isengard's court @Jauffr ?  Or is it a wider issue?

**Comment by Jauffr** [comment]
Looks as though something is causing them to randomly be generated sometimes still for all the immortal character cultures. Not often, yet they are there still 
![Screenshot 2023-02-26 202303](https://user-images.githubusercontent.com/108106660/221465925-4f3ed6df-06e4-4e3e-ba7d-6e5ec1a2d40e.png)

**Comment by Jauffr** [comment]
Oh! It is solved. Issue can be closed. They are being automatically converted to a correct culture after a monthly tick after generation
![Screenshot 2023-02-26 202938](https://user-images.githubusercontent.com/108106660/221466367-9575ca02-97d4-451f-a930-17d15aadbcbc.png)

**Comment by jj248** [comment]
Wunderbar.  It'll be something we need to keep an eye on for the lifetime of the mod, but no sense in keeping the issue open now this looks to be working for v3 content.  Closing.
